Make file output deterministic by sorting file data by ID
klaytonfaria/markdown-json pull request #25
Opened 2021-06-23 22:19 UTC by rosslh

It was bothering me that every time I rebuilt my project and ran markdown-json, it would change the order of the properties in the output file. This PR fixes it so that the order of the output data is determined by the file structure.

2021-07-07 12:47 UTC, klaytonfaria requested changes
@rosslh, 👏 Really nice contribution, thanks!

I'm wondering if introducing an output sorting maybe could be considered as a new feature. So, in this case, shouldn't be safer to define a toggle in our lib settings? 

Including a new argument `deterministicSorting` with default value as `false` on [/lib/helpme.js](https://github.com/klaytonfaria/markdown-json/blob/master/lib/helpme.js) and then checking if is enabled.

```javascript
if (settings.deterministicSorting) {
    data.data.sort((firstFile, secondFile) => firstFile.id < secondFile.id ? -1 : 1)
}
```

What do you think?

2021-07-08 03:35 UTC, rosslh commented
I added the feature toggle, let me know what you think! I called it "deterministicOrder" with the command-line option `-o` because if we wanted to call it "deterministicSorting", the options `-d`, `-D`, `-s`, and `-S` are already taken.

But "alphabeticalOrder" with `-a` or `-o` or "deterministicSorting" with a single-letter option that doesn't match are other alternatives to consider.

2021-07-23 00:28 UTC, rosslh commented
@klaytonfaria did you have a chance to take a look at my changes?

2021-07-23 00:36 UTC, klaytonfaria commented
> @klaytonfaria did you have a chance to take a look at my changes?

Hello @rosslh ! 
OMG! I didn't yet, sorry! I was 📴 but tomorrow I'll do it! Thank you for the heads-up!

2021-07-23 21:43 UTC, klaytonfaria approved these changes
🚀 LGTM!
Very nice PR, thanks! We can squash and merge!

2021-07-24 15:16 UTC, rosslh commented
Awesome, thanks @klaytonfaria! I'll leave merging with you because I don't have that ability. Much appreciated!

2021-08-02 19:09 UTC, merged